let data = [
  {
    GUID: "BCC-21056_20181025_LI_01_01",
    Category: "Delineadores",
    SubCategory: "Lápiz",
    Name: "Color Intense",
    Tone: "NOIR",
    Color: "#1b1b1b",
    Description: "Color intenso y textura suave",
  },
  {
    GUID: "BCC-21056_20181025_LI_01_02",
    Category: "Delineadores",
    SubCategory: "Lápiz",
    Name: "Color Intense",
    Tone: "BRUN",
    Color: "#2f110e",
    Description: "Color intenso y textura suave",
  },
  {
    GUID: "BCC-21056_20181025_LA_02_01",
    Category: "Máscaras",
    SubCategory: "Volumen",
    Name: "Opulence",
    Tone: "NOIR",
    Color: "#101010",
    Description: "Volumen inmediato",
  },
  {
    GUID: "BCC-21056_20181025_LA_03_01",
    Category: "Máscaras",
    SubCategory: "Alargamiento",
    Name: "Megacils Extend",
    Tone: "NOIR",
    Color: "#101010",
    Description: "Largo al instante",
  },
  {
    GUID: "BCC-21056_20181109_FD_02_01",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Mousse Matiffiant",
    Tone: "CLAIRE 1",
    Color: "#ebb785",
    Description: "Textura mousse y acabado mate",
  },
  {
    GUID: "BCC-21056_20181109_FD_02_02",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Mousse Matiffiant",
    Tone: "CLAIRE 2",
    Color: "#eaa87f",
    Description: "Textura mousse y acabado mate",
  },
  {
    GUID: "BCC-21056_20181109_FD_02_03",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Mousse Matiffiant",
    Tone: "CLAIRE 3",
    Color: "#e6ae82",
    Description: "Textura mousse y acabado mate",
  },
  {
    GUID: "BCC-21056_20181109_FD_02_04",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Mousse Matiffiant",
    Tone: "CLAIRE 4",
    Color: "#f0b27e",
    Description: "Textura mousse y acabado mate",
  },
  {
    GUID: "BCC-21056_20181109_FD_02_05",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Mousse Matiffiant",
    Tone: "MEDIUM 5",
    Color: "#e1b98f",
    Description: "Textura mousse y acabado mate",
  },
  {
    GUID: "BCC-21056_20181109_FD_02_06",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Mousse Matiffiant",
    Tone: "MEDIUM 6",
    Color: "#e3aa72",
    Description: "Textura mousse y acabado mate",
  },
  {
    GUID: "BCC-21056_20181109_FD_02_07",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Mousse Matiffiant",
    Tone: "MEDIUM 7",
    Color: "#bc8865",
    Description: "Textura mousse y acabado mate",
  },
  {
    GUID: "BCC-21056_20181109_FD_02_08",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Mousse Matiffiant",
    Tone: "OBSCURE 8",
    Color: "#a17654",
    Description: "Textura mousse y acabado mate",
  },
  {
    GUID: "BCC-21056_20181109_FD_02_09",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Mousse Matiffiant",
    Tone: "OBSCURE 9",
    Color: "#73441e",
    Description: "Textura mousse y acabado mate",
  },
  {
    GUID: "BCC-21056_20181025_FD_03_01",
    Category: "Polvos",
    SubCategory: "Mate",
    Name: "Compactos Doble Uso Ed. De Lujo",
    Tone: "CLAIRE 1-2-3",
    Color: "#f5c4a1",
    Description: "Cubre imperfecciones, matifica",
  },
  {
    GUID: "BCC-21056_20181025_FD_03_02",
    Category: "Polvos",
    SubCategory: "Mate",
    Name: "Compactos Doble Uso Ed. De Lujo",
    Tone: "CLAIRE 4",
    Color: "#fcc09c",
    Description: "Cubre imperfecciones, matifica",
  },
  {
    GUID: "BCC-21056_20181025_FD_03_03",
    Category: "Polvos",
    SubCategory: "Mate",
    Name: "Compactos Doble Uso Ed. De Lujo",
    Tone: "MEDIUM 5",
    Color: "#f1b38d",
    Description: "Cubre imperfecciones, matifica",
  },
  {
    GUID: "BCC-21056_20181025_FD_03_04",
    Category: "Polvos",
    SubCategory: "Mate",
    Name: "Compactos Doble Uso Ed. De Lujo",
    Tone: "MEDIUM 6",
    Color: "#f1ae81",
    Description: "Cubre imperfecciones, matifica",
  },
  {
    GUID: "BCC-21056_20181025_FD_03_05",
    Category: "Polvos",
    SubCategory: "Mate",
    Name: "Compactos Doble Uso Ed. De Lujo",
    Tone: "MEDIUM 7",
    Color: "#e7a985",
    Description: "Cubre imperfecciones, matifica",
  },
  {
    GUID: "BCC-21056_20181025_FD_03_06",
    Category: "Polvos",
    SubCategory: "Mate",
    Name: "Compactos Doble Uso Ed. De Lujo",
    Tone: "OBSCURE 8-9",
    Color: "#f5a36c",
    Description: "Cubre imperfecciones, matifica",
  },
  {
    GUID: "BCC-21056_20181024_LS_06_19",
    Category: "Labiales",
    SubCategory: "Rojos",
    Name: "Rouge L'Intense Barra",
    Tone: "ROUGE",
    Color: "#a51837",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_06_18",
    Category: "Labiales",
    SubCategory: "Nude",
    Name: "Rouge L'Intense Barra",
    Tone: "NUDE",
    Color: "#af756b",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_06_17",
    Category: "Labiales",
    SubCategory: "Nude",
    Name: "Rouge L'Intense Barra",
    Tone: "ABRICOT",
    Color: "#b46e63",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_06_13",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Rouge L'Intense Barra",
    Tone: "BERRY ROSELLE",
    Color: "#af575f",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_06_12",
    Category: "Labiales",
    SubCategory: "Vinos",
    Name: "Rouge L'Intense Barra",
    Tone: "ROUGE MALBEC",
    Color: "#853435",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_06_11",
    Category: "Labiales",
    SubCategory: "Vinos",
    Name: "Rouge L'Intense Barra",
    Tone: "VIN INTENSE",
    Color: "#892e42",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181109_FD_04_01",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Rejuvenecedora",
    Tone: "CLAIRE 1",
    Color: "#e5af6f",
    Description: "Cubre signos de la edad",
  },
  {
    GUID: "BCC-21056_20181109_FD_04_02",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Rejuvenecedora",
    Tone: "CLAIRE 2",
    Color: "#f1a86e",
    Description: "Cubre signos de la edad",
  },
  {
    GUID: "BCC-21056_20181109_FD_04_03",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Rejuvenecedora",
    Tone: "CLAIRE 3",
    Color: "#e19d51",
    Description: "Cubre signos de la edad",
  },
  {
    GUID: "BCC-21056_20181109_FD_04_04",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Rejuvenecedora",
    Tone: "CLAIRE 4",
    Color: "#df9f6d",
    Description: "Cubre signos de la edad",
  },
  {
    GUID: "BCC-21056_20181109_FD_04_05",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Rejuvenecedora",
    Tone: "MEDIUM 5",
    Color: "#d9aa78",
    Description: "Cubre signos de la edad",
  },
  {
    GUID: "BCC-21056_20181109_FD_04_06",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Rejuvenecedora",
    Tone: "MEDIUM 6",
    Color: "#c59360",
    Description: "Cubre signos de la edad",
  },
  {
    GUID: "BCC-21056_20181109_FD_04_07",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Rejuvenecedora",
    Tone: "MEDIUM 7",
    Color: "#b07956",
    Description: "Cubre signos de la edad",
  },
  {
    GUID: "BCC-21056_20181109_FD_04_08",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Rejuvenecedora",
    Tone: "OBSCURE 8",
    Color: "#9f6d33",
    Description: "Cubre signos de la edad",
  },
  {
    GUID: "BCC-21056_20181109_FD_04_09",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Rejuvenecedora",
    Tone: "OBSCURE 9",
    Color: "#834e24",
    Description: "Cubre signos de la edad",
  },
  {
    GUID: "BCC-21056_20181109_FD_05_01",
    Category: "Bases",
    SubCategory: "Natural",
    Name: "Corrector Facial En Lapiz",
    Tone: "CLAIRE 1-2-3",
    Color: "#f9c5a0",
    Description: "Cubre bolsas y ojeras",
  },
  {
    GUID: "BCC-21056_20181109_FD_05_02",
    Category: "Bases",
    SubCategory: "Natural",
    Name: "Corrector Facial En Lapiz",
    Tone: "CLAIRE 4",
    Color: "#f5b98e",
    Description: "Cubre bolsas y ojeras",
  },
  {
    GUID: "BCC-21056_20181109_FD_05_03",
    Category: "Bases",
    SubCategory: "Natural",
    Name: "Corrector Facial En Lapiz",
    Tone: "MEDIUM 5-6",
    Color: "#d0a688",
    Description: "Cubre bolsas y ojeras",
  },
  {
    GUID: "BCC-21056_20181109_FD_05_04",
    Category: "Bases",
    SubCategory: "Natural",
    Name: "Corrector Facial En Lapiz",
    Tone: "MEDIUM 7",
    Color: "#be8861",
    Description: "Cubre bolsas y ojeras",
  },
  {
    GUID: "BCC-21056_20181109_FD_05_05",
    Category: "Bases",
    SubCategory: "Natural",
    Name: "Corrector Facial En Lapiz",
    Tone: "OBSCURE 8-9",
    Color: "#ac7139",
    Description: "Cubre bolsas y ojeras",
  },
  {
    GUID: "BCC-21056_20181025_BL_01_01",
    Category: "Rubores",
    SubCategory: "-",
    Name: "Blush Delicat",
    Tone: "EDEN",
    Color: "#ed958c",
    Description: "Acabado natural, Alta adherenc",
  },
  {
    GUID: "BCC-21056_20181025_BL_01_02",
    Category: "Rubores",
    SubCategory: "-",
    Name: "Blush Delicat",
    Tone: "ROSE THÉ",
    Color: "#ef997d",
    Description: "Acabado natural, Alta adherenc",
  },
  {
    GUID: "BCC-21056_20181025_BL_01_03",
    Category: "Rubores",
    SubCategory: "-",
    Name: "Blush Delicat",
    Tone: "ABRICOT DORE",
    Color: "#ec8566",
    Description: "Acabado natural, Alta adherenc",
  },
  {
    GUID: "BCC-21056_20181025_BL_01_04",
    Category: "Rubores",
    SubCategory: "-",
    Name: "Blush Delicat",
    Tone: "DOLCE SAND",
    Color: "#e28e6c",
    Description: "Acabado natural, Alta adherenc",
  },
  {
    GUID: "BCC-21056_20181025_BL_01_05",
    Category: "Rubores",
    SubCategory: "-",
    Name: "Blush Delicat",
    Tone: "BRONZE",
    Color: "#cb8c72",
    Description: "Acabado natural, Alta adherenc",
  },
  {
    GUID: "BCC-21056_20181025_BL_01_06",
    Category: "Rubores",
    SubCategory: "-",
    Name: "Blush Delicat",
    Tone: "PURE ROSE",
    Color: "#d47588",
    Description: "Acabado natural, Alta adherenc",
  },
  {
    GUID: "BCC-21056_20181024_LS_06_06",
    Category: "Labiales",
    SubCategory: "Marrones",
    Name: "Rouge L'Intense Barra",
    Tone: "MOCCA",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181025_FD_02_01",
    Category: "Polvos",
    SubCategory: "Mate",
    Name: "Control De Brillo FM",
    Tone: "CLAIRE 1-2-3",
    Color: "#f2c8a1",
    Description: "Eliminan el exceso de brillo",
  },
  {
    GUID: "BCC-21056_20181025_FD_02_02",
    Category: "Polvos",
    SubCategory: "Mate",
    Name: "Control De Brillo FM",
    Tone: "CLAIRE 4",
    Color: "#f9c39e",
    Description: "Eliminan el exceso de brillo",
  },
  {
    GUID: "BCC-21056_20181025_FD_02_03",
    Category: "Polvos",
    SubCategory: "Mate",
    Name: "Control De Brillo FM",
    Tone: "MEDIUM 5",
    Color: "#f1b185",
    Description: "Eliminan el exceso de brillo",
  },
  {
    GUID: "BCC-21056_20181025_FD_02_04",
    Category: "Polvos",
    SubCategory: "Mate",
    Name: "Control De Brillo FM",
    Tone: "MEDIUM 6",
    Color: "#f0a874",
    Description: "Eliminan el exceso de brillo",
  },
  {
    GUID: "BCC-21056_20181025_FD_02_05",
    Category: "Polvos",
    SubCategory: "Mate",
    Name: "Control De Brillo FM",
    Tone: "MEDIUM 7",
    Color: "#e2ae86",
    Description: "Eliminan el exceso de brillo",
  },
  {
    GUID: "BCC-21056_20181025_FD_02_06",
    Category: "Polvos",
    SubCategory: "Mate",
    Name: "Control De Brillo FM",
    Tone: "OBSCURE 8-9",
    Color: "#e0a06f",
    Description: "Eliminan el exceso de brillo",
  },
  {
    GUID: "BCC-21056_20181024_LS_06_05",
    Category: "Labiales",
    SubCategory: "Morados",
    Name: "Rouge L'Intense Barra",
    Tone: "MORA",
    Color: "#732f49",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181025_LS_02_07",
    Category: "Labiales",
    SubCategory: "Rojos",
    Name: "Concentré Total",
    Tone: "ROUGE CORAIL",
    Color: "#bd233e",
    Description: "10 beneficios en 1",
  },
  {
    GUID: "BCC-21056_20181025_LS_02_09",
    Category: "Labiales",
    SubCategory: "Fucsias",
    Name: "Concentré Total Labios",
    Tone: "FUCSIA RADIANT",
    Color: "#d40073",
    Description: "10 beneficios en 1",
  },
  {
    GUID: "BCC-21056_20181025_LA_04_01",
    Category: "Máscaras",
    SubCategory: "Alargamiento",
    Name: "Multi-Extense",
    Tone: "NOIR",
    Color: "#101010",
    Description: "Efecto largo extremo",
  },
  {
    GUID: "BCC-21056_20181025_FD_01_01",
    Category: "Polvos",
    SubCategory: "Mate",
    Name: "Polvos Compactos Fps 15",
    Tone: "CLAIRE 1-2-3",
    Color: "#fac8a1",
    Description: "Hasta 24 hora sin retoques",
  },
  {
    GUID: "BCC-21056_20181025_FD_01_02",
    Category: "Polvos",
    SubCategory: "Mate",
    Name: "Polvos Compactos Fps 15",
    Tone: "CLAIRE 4",
    Color: "#ffc19e",
    Description: "Hasta 24 hora sin retoques",
  },
  {
    GUID: "BCC-21056_20181025_FD_01_03",
    Category: "Polvos",
    SubCategory: "Mate",
    Name: "Polvos Compactos Fps 15",
    Tone: "MEDIUM 5",
    Color: "#eab186",
    Description: "Hasta 24 hora sin retoques",
  },
  {
    GUID: "BCC-21056_20181025_FD_01_04",
    Category: "Polvos",
    SubCategory: "Mate",
    Name: "Polvos Compactos Fps 15",
    Tone: "MEDIUM 6",
    Color: "#e9a36e",
    Description: "Hasta 24 hora sin retoques",
  },
  {
    GUID: "BCC-21056_20181025_FD_01_05",
    Category: "Polvos",
    SubCategory: "Mate",
    Name: "Polvos Compactos Fps 15",
    Tone: "MEDIUM 7",
    Color: "#ecaf8c",
    Description: "Hasta 24 hora sin retoques",
  },
  {
    GUID: "BCC-21056_20181025_FD_01_06",
    Category: "Polvos",
    SubCategory: "Mate",
    Name: "Polvos Compactos Fps 15",
    Tone: "OBSCURE 8-9",
    Color: "#dda37a",
    Description: "Hasta 24 hora sin retoques",
  },
  {
    GUID: "BCC-21056_20181025_LI_04_06",
    Category: "Delineadores",
    SubCategory: "Líquido",
    Name: "Liner Illimité",
    Tone: "NOIR",
    Color: "#1e1e1e",
    Description: "Color intenso y larga duración",
  },
  {
    GUID: "BCC-21056_20181025_LI_04_05",
    Category: "Delineadores",
    SubCategory: "Líquido",
    Name: "Liner Illimité",
    Tone: "BRUN",
    Color: "#6c4434",
    Description: "Color intenso y larga duración",
  },
  {
    GUID: "BCC-21056_20181025_LI_04_04",
    Category: "Delineadores",
    SubCategory: "Líquido",
    Name: "Liner Illimité",
    Tone: "BLEU",
    Color: "#313a65",
    Description: "Color intenso y larga duración",
  },
  {
    GUID: "BCC-21056_20181025_LI_04_03",
    Category: "Delineadores",
    SubCategory: "Líquido",
    Name: "Liner Illimité",
    Tone: "BURGUNDY",
    Color: "#772345",
    Description: "Color intenso y larga duración",
  },
  {
    GUID: "BCC-21056_20181024_LS_01_10",
    Category: "Labiales",
    SubCategory: "Fucsias",
    Name: "Dúo Amplifiant",
    Tone: "FUCSIA VIOLET",
    Color: "#a74a72",
    Description: "Mayor definición y volumen",
  },
  {
    GUID: "BCC-21056_20181024_LS_01_09",
    Category: "Labiales",
    SubCategory: "Morados",
    Name: "Dúo Amplifiant",
    Tone: "BERRY VIOLET",
    Color: "#a76171",
    Description: "Mayor definición y volumen",
  },
  {
    GUID: "BCC-21056_20181024_LS_01_08",
    Category: "Labiales",
    SubCategory: "Morados",
    Name: "Dúo Amplifiant",
    Tone: "VIOLET MALVE",
    Color: "#895465",
    Description: "Mayor definición y volumen",
  },
  {
    GUID: "BCC-21056_20181024_LS_01_05",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Dúo Amplifiant",
    Tone: "ROSEWOOD",
    Color: "#c87a79",
    Description: "Mayor definición y volumen",
  },
  {
    GUID: "BCC-21056_20181024_LS_01_04",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Dúo Amplifiant",
    Tone: "ROSE TERRACOTA",
    Color: "#913f3e",
    Description: "Mayor definición y volumen",
  },
  {
    GUID: "BCC-21056_20181024_LS_01_03",
    Category: "Labiales",
    SubCategory: "Marrones",
    Name: "Dúo Amplifiant",
    Tone: "CARAMEL MOCHA",
    Color: "#935844",
    Description: "Mayor definición y volumen",
  },
  {
    GUID: "BCC-21056_20181024_LS_01_07",
    Category: "Labiales",
    SubCategory: "Fucsias",
    Name: "Dúo Amplifiant",
    Tone: "RASPBERRY",
    Color: "#b95e63",
    Description: "Mayor definición y volumen",
  },
  {
    GUID: "BCC-21056_20181024_LS_01_02",
    Category: "Labiales",
    SubCategory: "Vinos",
    Name: "Dúo Amplifiant",
    Tone: "VIN INTENSE",
    Color: "#8e3d49",
    Description: "Mayor definición y volumen",
  },
  {
    GUID: "BCC-21056_20181024_LS_01_06",
    Category: "Labiales",
    SubCategory: "Vinos",
    Name: "Dúo Amplifiant",
    Tone: "VIN ROUGE",
    Color: "#952132",
    Description: "Mayor definición y volumen",
  },
  {
    GUID: "BCC-21056_20181024_LS_01_01",
    Category: "Labiales",
    SubCategory: "Rojos",
    Name: "Dúo Amplifiant",
    Tone: "ROUGE BOURGOGNE",
    Color: "#881e2c",
    Description: "Mayor definición y volumen",
  },
  {
    GUID: "BCC-21056_20181025_FD_04_03",
    Category: "Polvos",
    SubCategory: "Natural",
    Name: "Polvos Sueltos Extra Finos",
    Tone: "PORCELAINE",
    Color: "#c4927c",
    Description: "Emparejan, protegen y sellan",
  },
  {
    GUID: "BCC-21056_20181025_FD_04_01",
    Category: "Polvos",
    SubCategory: "Natural",
    Name: "Polvos Sueltos Extra Finos",
    Tone: "TRASLUCIDE",
    Color: "#f1c4a4",
    Description: "Emparejan, protegen y sellan",
  },
  {
    GUID: "BCC-21056_20181025_FD_04_02",
    Category: "Polvos",
    SubCategory: "Natural",
    Name: "Polvos Sueltos Extra Finos",
    Tone: "SANTE",
    Color: "#e3ab86",
    Description: "Emparejan, protegen y sellan",
  },
  {
    GUID: "BCC-21056_20181024_LS_06_27",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Rouge L'Intense Barra",
    Tone: "ROSE LATTE",
    Color: "#c26790",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_06_22",
    Category: "Labiales",
    SubCategory: "Nude",
    Name: "Rouge L'Intense Barra",
    Tone: "CRÉME",
    Color: "#d4999b",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_06_23",
    Category: "Labiales",
    SubCategory: "Marrones",
    Name: "Rouge L'Intense Barra",
    Tone: "CHOCOLAT",
    Color: "#703e33",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_06_24",
    Category: "Labiales",
    SubCategory: "Marrones",
    Name: "Rouge L'Intense Barra",
    Tone: "DARK CARAMEL",
    Color: "#985651",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_06_25",
    Category: "Labiales",
    SubCategory: "Fucsias",
    Name: "Rouge L'Intense Barra",
    Tone: "ROUGE FRAMBOISE",
    Color: "#d13471",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_06_26",
    Category: "Labiales",
    SubCategory: "Vinos",
    Name: "Rouge L'Intense Barra",
    Tone: "CHERRY INTENSE",
    Color: "#8f2759",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181025_LI_04_02",
    Category: "Delineadores",
    SubCategory: "Líquido",
    Name: "Liner Illimité",
    Tone: "METALLIC",
    Color: "#c1c1c9",
    Description: "Color intenso y larga duración",
  },
  {
    GUID: "BCC-21056_20181025_LI_04_01",
    Category: "Delineadores",
    SubCategory: "Líquido",
    Name: "Liner Illimité",
    Tone: "GOLDEN",
    Color: "#d9a34c",
    Description: "Color intenso y larga duración",
  },
  {
    GUID: "BCC-21056_20190307_LA_01_01",
    Category: "Máscaras",
    SubCategory: "Volumen",
    Name: "Hypervolume",
    Tone: "NOIR",
    Color: "#101010",
    Description: "Más volumen, más largo",
  },
  {
    GUID: "BCC-21056_20201001_FD_01_01",
    Category: "Polvos",
    SubCategory: "Natural",
    Name: "Translucent",
    Tone: "TRANSLÚCIDO",
    Color: "#ffdcc4",
    Description: "Deja respirar tu piel",
  },
  {
    GUID: "BCC-21056_20200928_FCP_01_03",
    Category: "Polvos",
    SubCategory: "Natural",
    Name: "Contour Parfait",
    Tone: "COCOA PALETTE",
    Description: "Perfila y difumina",
  },
  {
    GUID: "BCC-21056_20200926_LS_01_01",
    Category: "Labiales",
    SubCategory: "Rojos",
    Name: "Dúo Hydra Matte",
    Tone: "PURE RED",
    Color: "#b62540",
    Description: "Color intenso con hidratación",
  },
  {
    GUID: "BCC-21056_20200926_LS_01_02",
    Category: "Labiales",
    SubCategory: "Vinos",
    Name: "Dúo Hydra Matte",
    Tone: "VIN INTENSE",
    Color: "#6d0c2e",
    Description: "Color intenso con hidratación",
  },
  {
    GUID: "BCC-21056_20200926_LS_01_03",
    Category: "Labiales",
    SubCategory: "Fucsias",
    Name: "Dúo Hydra Matte",
    Tone: "BERRY RICHE",
    Color: "#932b71",
    Description: "Color intenso con hidratación",
  },
  {
    GUID: "BCC-21056_20200926_LS_01_04",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Dúo Hydra Matte",
    Tone: "VELVET ROSE",
    Color: "#bb6b6c",
    Description: "Color intenso con hidratación",
  },
  {
    GUID: "BCC-21056_20200926_LS_01_05",
    Category: "Labiales",
    SubCategory: "Nude",
    Name: "Dúo Hydra Matte",
    Tone: "DEEP APRICOT",
    Color: "#c26061",
    Description: "Color intenso con hidratación",
  },
  {
    GUID: "BCC-21056_20200926_LS_01_06",
    Category: "Labiales",
    SubCategory: "Marrones",
    Name: "Dúo Hydra Matte",
    Tone: "AUTUMN CARAMEL",
    Color: "#904d3a",
    Description: "Color intenso con hidratación",
  },
  {
    GUID: "BCC-21056_20200926_LS_01_07",
    Category: "Labiales",
    SubCategory: "Rojos",
    Name: "Dúo Hydra Matte",
    Tone: "ROUGE RUBI",
    Color: "#6e1817",
    Description: "Color intenso con hidratación",
  },
  {
    GUID: "BCC-21056_20200926_LS_01_08",
    Category: "Labiales",
    SubCategory: "Morados",
    Name: "Dúo Hydra Matte",
    Tone: "VIOLET SUPREME",
    Color: "#84047d",
    Description: "Color intenso con hidratación",
  },
  {
    GUID: "BCC-21056_20200926_LS_01_09",
    Category: "Labiales",
    SubCategory: "Fucsias",
    Name: "Dúo Hydra Matte",
    Tone: "DEEP FUCSIA",
    Color: "#9f0664",
    Description: "Color intenso con hidratación",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_25",
    Category: "Labiales",
    SubCategory: "Vinos",
    Name: "Infini Dorado Mate",
    Tone: "ROYAL GRAPE",
    Color: "#561728",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20201008_FD_02_01",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Aclaradora De Manchas Clarité",
    Tone: "110C",
    Color: "#f8bc8c",
    Description: "Minimiza y aclara de manchas",
  },
  {
    GUID: "BCC-21056_20201008_FD_02_06",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Aclaradora De Manchas Clarité",
    Tone: "170N",
    Color: "#dda677",
    Description: "Minimiza y aclara de manchas",
  },
  {
    GUID: "BCC-21056_20201008_FD_02_07",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Aclaradora De Manchas Clarité",
    Tone: "180F",
    Color: "#d8a27e",
    Description: "Minimiza y aclara de manchas",
  },
  {
    GUID: "BCC-21056_20201008_FD_02_09",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Aclaradora De Manchas Clarité",
    Tone: "210F",
    Color: "#d2986a",
    Description: "Minimiza y aclara de manchas",
  },
  {
    GUID: "BCC-21056_20201008_FD_02_10",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Aclaradora De Manchas Clarité",
    Tone: "220C",
    Color: "#ca9765",
    Description: "Minimiza y aclara de manchas",
  },
  {
    GUID: "BCC-21056_20201008_FD_02_11",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Aclaradora De Manchas Clarité",
    Tone: "230N",
    Color: "#b8855e",
    Description: "Minimiza y aclara de manchas",
  },
  {
    GUID: "BCC-21056_20201008_FD_02_15",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Aclaradora De Manchas Clarité",
    Tone: "270C",
    Color: "#bf8652",
    Description: "Minimiza y aclara de manchas",
  },
  {
    GUID: "BCC-21056_20201008_FD_02_19",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Aclaradora De Manchas Clarité",
    Tone: "310C",
    Color: "#c78852",
    Description: "Minimiza y aclara de manchas",
  },
  {
    GUID: "BCC-21056_20201008_FD_02_23",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Aclaradora De Manchas Clarité",
    Tone: "350N",
    Color: "#b77e4d",
    Description: "Minimiza y aclara de manchas",
  },
  {
    GUID: "BCC-21056_20210626_FD_01_01",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Matte Pro Défense",
    Tone: "CREME",
    Color: "#DEAD8D",
    Description: "5 beneficios en 1",
  },
  {
    GUID: "BCC-21056_20210626_FD_01_07",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Matte Pro Défense",
    Tone: "CHAMPAGNE",
    Color: "#DDA98A",
    Description: "5 beneficios en 1",
  },
  {
    GUID: "BCC-21056_20210626_FD_01_10",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Matte Pro Défense",
    Tone: "LATTE",
    Color: "#CB9781",
    Description: "5 beneficios en 1",
  },
  {
    GUID: "BCC-21056_20210626_FD_01_06",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Matte Pro Défense",
    Tone: "CARAMEL",
    Color: "#D69F76",
    Description: "5 beneficios en 1",
  },
  {
    GUID: "BCC-21056_20210626_FD_01_03",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Matte Pro Défense",
    Tone: "BEIGE",
    Color: "#D69F76",
    Description: "5 beneficios en 1",
  },
  {
    GUID: "BCC-21056_20210626_FD_01_09",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Matte Pro Défense",
    Tone: "ALMENDRA",
    Color: "#D69D73",
    Description: "5 beneficios en 1",
  },
  {
    GUID: "BCC-21056_20210626_FD_01_02",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Matte Pro Défense",
    Tone: "AVELLANA",
    Color: "#AD7552",
    Description: "5 beneficios en 1",
  },
  {
    GUID: "BCC-21056_20210626_FD_01_05",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Matte Pro Défense",
    Tone: "CAPUCCINO",
    Color: "#BA7B5C",
    Description: "5 beneficios en 1",
  },
  {
    GUID: "BCC-21056_20210626_FD_01_04",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Matte Pro Défense",
    Tone: "CACAO",
    Color: "#B07650",
    Description: "5 beneficios en 1",
  },
  {
    GUID: "BCC-21056_20210626_FD_01_12",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Matte Pro Défense",
    Tone: "MOKACCINO",
    Color: "#B47758",
    Description: "5 beneficios en 1",
  },
  {
    GUID: "BCC-21056_20210626_FD_01_11",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Matte Pro Défense",
    Tone: "MOKA",
    Color: "#8C5536",
    Description: "5 beneficios en 1",
  },
  {
    GUID: "BCC-21056_20210626_FD_01_08",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Matte Pro Défense",
    Tone: "CHOCOLAT",
    Color: "#6A4127",
    Description: "5 beneficios en 1",
  },
  {
    GUID: "BCC-21056_20200927_SD_01_01",
    Category: "Sombras",
    SubCategory: "Nude",
    Name: "La Palette",
    Tone: "RADIANT",
    Description: "Más duración y color",
  },
  {
    GUID: "BCC-21056_20200927_SD_01_02",
    Category: "Sombras",
    SubCategory: "Cherry",
    Name: "La Palette",
    Tone: "ROMANTIC",
    Description: "Más duración y color",
  },
  {
    GUID: "BCC-21056_20200926_LS_01_10",
    Category: "Labiales",
    SubCategory: "Corales",
    Name: "Dúo Hydra Matte",
    Tone: "CORAL PEACH",
    Color: "#d37669",
    Description: "Color intenso con hidratación",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_24",
    Category: "Labiales",
    SubCategory: "Rojos",
    Name: "Infini Dorado Metalizado",
    Tone: "ROUGE PASSION",
    Color: "#bb0015",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_23",
    Category: "Labiales",
    SubCategory: "Morados",
    Name: "Infini Dorado Metalizado",
    Tone: "FRAMBOISE",
    Color: "#7E1B56",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_26",
    Category: "Labiales",
    SubCategory: "Morados",
    Name: "Infini Dorado Metalizado",
    Tone: "VIOLET GOLD",
    Color: "#773A65",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210625_FD_01_01",
    Category: "Bases",
    SubCategory: "Natural",
    Name: "Concentré Total Sérum",
    Tone: "CREME",
    Color: "#EDB999",
    Description: "5 beneficios en 1",
  },
  {
    GUID: "BCC-21056_20210625_FD_01_03",
    Category: "Bases",
    SubCategory: "Natural",
    Name: "Concentré Total Sérum",
    Tone: "CHAMPAGNE",
    Color: "#dbab8b",
    Description: "5 beneficios en 1",
  },
  {
    GUID: "BCC-21056_20210625_FD_01_02",
    Category: "Bases",
    SubCategory: "Natural",
    Name: "Concentré Total Sérum",
    Tone: "LATTE",
    Color: "#c7937f",
    Description: "5 beneficios en 1",
  },
  {
    GUID: "BCC-21056_20210625_FD_01_04",
    Category: "Bases",
    SubCategory: "Natural",
    Name: "Concentré Total Sérum",
    Tone: "CARAMEL",
    Color: "#E9B392",
    Description: "5 beneficios en 1",
  },
  {
    GUID: "BCC-21056_20210625_FD_01_05",
    Category: "Bases",
    SubCategory: "Natural",
    Name: "Concentré Total Sérum",
    Tone: "BEIGE",
    Color: "#c69576",
    Description: "5 beneficios en 1",
  },
  {
    GUID: "BCC-21056_20210625_FD_01_06",
    Category: "Bases",
    SubCategory: "Natural",
    Name: "Concentré Total Sérum",
    Tone: "ALMENDRA",
    Color: "#c5906b",
    Description: "5 beneficios en 1",
  },
  {
    GUID: "BCC-21056_20210625_FD_01_07",
    Category: "Bases",
    SubCategory: "Natural",
    Name: "Concentré Total Sérum",
    Tone: "CAPUCCINO",
    Color: "#CA9069",
    Description: "5 beneficios en 1",
  },
  {
    GUID: "BCC-21056_20210625_FD_01_08",
    Category: "Bases",
    SubCategory: "Natural",
    Name: "Concentré Total Sérum",
    Tone: "CACAO",
    Color: "#C68A5D",
    Description: "5 beneficios en 1",
  },
  {
    GUID: "BCC-21056_20210625_FD_01_09",
    Category: "Bases",
    SubCategory: "Natural",
    Name: "Concentré Total Sérum",
    Tone: "MOKACCINO",
    Color: "#BB8059",
    Description: "5 beneficios en 1",
  },
  {
    GUID: "BCC-21056_20210625_FD_01_10",
    Category: "Bases",
    SubCategory: "Natural",
    Name: "Concentré Total Sérum",
    Tone: "MOKA",
    Color: "#A36944",
    Description: "5 beneficios en 1",
  },
  {
    GUID: "BCC-21056_20210625_FD_01_11",
    Category: "Bases",
    SubCategory: "Natural",
    Name: "Concentré Total Sérum",
    Tone: "CHOCOLAT",
    Color: "#80543B",
    Description: "5 beneficios en 1",
  },
  {
    GUID: "BCC-21056_20210315_LI_01_01",
    Category: "Delineadores",
    SubCategory: "Líquido",
    Name: "Liner D'Impact",
    Tone: "NOIR",
    Color: "#040404",
    Description: "Máxima intensidad y duración",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_36",
    Category: "Labiales",
    SubCategory: "Rojos",
    Name: "Infini Absolu",
    Tone: "RED SAUVAGE",
    Color: "#ba0001",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_31",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Infini Absolu",
    Tone: "ROSE GRANADA",
    Color: "#ae4756",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_10",
    Category: "Labiales",
    SubCategory: "Marrones",
    Name: "Infini Absolu",
    Tone: "COCOA MOUSSE",
    Color: "#6e4647",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_02",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Infini Absolu",
    Tone: "ROSE ELEGANCE",
    Color: "#cd5b5e",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_05",
    Category: "Labiales",
    SubCategory: "Rojos",
    Name: "Infini Absolu",
    Tone: "ROUGE PETAL",
    Color: "#9e1e20",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_03",
    Category: "Labiales",
    SubCategory: "Corales",
    Name: "Infini Absolu",
    Tone: "CORAL VIVANT",
    Color: "#dc6864",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_13",
    Category: "Labiales",
    SubCategory: "Morados",
    Name: "Infini Absolu",
    Tone: "DEEP BERRY",
    Color: "#481f2f",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_16",
    Category: "Labiales",
    SubCategory: "Morados",
    Name: "Infini Absolu",
    Tone: "BERRY VIBRANT",
    Color: "#783e5c",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_14",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Infini Absolu",
    Tone: "MALVE DELICE",
    Color: "#a95559",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_19",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Infini Absolu",
    Tone: "CARMINE",
    Color: "#9d4a46",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_18",
    Category: "Labiales",
    SubCategory: "Nude",
    Name: "Infini Absolu",
    Tone: "NUDE ROSE",
    Color: "#b16764",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_41",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Infini Absolu",
    Tone: "TULIP ROSE",
    Color: "#9d5f73",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_42",
    Category: "Labiales",
    SubCategory: "Rojos",
    Name: "Infini Absolu",
    Tone: "HOT BRANDY",
    Color: "#5e0911",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_43",
    Category: "Labiales",
    SubCategory: "Vinos",
    Name: "Infini Absolu",
    Tone: "VIN MORA",
    Color: "#8b336b",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_44",
    Category: "Labiales",
    SubCategory: "Vinos",
    Name: "Infini Absolu",
    Tone: "VIN INTENSE",
    Color: "#541e1e",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181109_FD_01_01",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Hydra Absolute",
    Tone: "CLAIRE 1",
    Color: "#c09a62",
    Description: "Hidratación hasta por 24 horas",
  },
  {
    GUID: "BCC-21056_20181109_FD_01_02",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Hydra Absolute",
    Tone: "CLAIRE 2",
    Color: "#cda376",
    Description: "Hidratación hasta por 24 horas",
  },
  {
    GUID: "BCC-21056_20181109_FD_01_03",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Hydra Absolute",
    Tone: "CLAIRE 3",
    Color: "#ce9e61",
    Description: "Hidratación hasta por 24 horas",
  },
  {
    GUID: "BCC-21056_20181109_FD_01_04",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Hydra Absolute",
    Tone: "CLAIRE 4",
    Color: "#cb986f",
    Description: "Hidratación hasta por 24 horas",
  },
  {
    GUID: "BCC-21056_20181109_FD_01_05",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Hydra Absolute",
    Tone: "MEDIUM 5",
    Color: "#c09c6c",
    Description: "Hidratación hasta por 24 horas",
  },
  {
    GUID: "BCC-21056_20181109_FD_01_06",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Hydra Absolute",
    Tone: "MEDIUM 6",
    Color: "#ad8151",
    Description: "Hidratación hasta por 24 horas",
  },
  {
    GUID: "BCC-21056_20181109_FD_01_07",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Hydra Absolute",
    Tone: "MEDIUM 7",
    Color: "#a27856",
    Description: "Hidratación hasta por 24 horas",
  },
  {
    GUID: "BCC-21056_20181109_FD_01_08",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Hydra Absolute",
    Tone: "OBSCURE 8",
    Color: "#9b7348",
    Description: "Hidratación hasta por 24 horas",
  },
  {
    GUID: "BCC-21056_20181109_FD_01_09",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Hydra Absolute",
    Tone: "OBSCURE 9",
    Color: "#5c371e",
    Description: "Hidratación hasta por 24 horas",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_46",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Rouge L'Intense Líquido",
    Tone: "ROSÉ CHARME",
    Color: "#b8737f",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_47",
    Category: "Labiales",
    SubCategory: "Morados",
    Name: "Rouge L'Intense Líquido",
    Tone: "MALVA ALLURE",
    Color: "#95568b",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_48",
    Category: "Labiales",
    SubCategory: "Nude",
    Name: "Rouge L'Intense Líquido",
    Tone: "MOCCA FRANCE",
    Color: "#be8e88",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_03_01",
    Category: "Labiales",
    SubCategory: "Nude",
    Name: "Ultra Balm",
    Tone: "NUDE TRANSLUCIDE",
    Color: "#f4ac96",
    Description: "Hidrata, Restaura y Protege",
  },
  {
    GUID: "BCC-21056_20181024_LS_03_02",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Ultra Balm",
    Tone: "CORAL PETALE",
    Color: "#f54d5e",
    Description: "Hidrata, Restaura y Protege",
  },
  {
    GUID: "BCC-21056_20181024_LS_03_03",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Ultra Balm",
    Tone: "ROSE PARADISE",
    Color: "#ff76a0",
    Description: "Hidrata, Restaura y Protege",
  },
  {
    GUID: "BCC-21056_20181024_LS_03_05",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Ultra Balm",
    Tone: "ROSE COTTON",
    Color: "#ff9db6",
    Description: "Hidrata, Restaura y Protege",
  },
  {
    GUID: "BCC-21056_20181024_LS_03_06",
    Category: "Labiales",
    SubCategory: "Nude",
    Name: "Ultra Balm",
    Tone: "CERISE BRISE",
    Color: "#d75e67",
    Description: "Hidrata, Restaura y Protege",
  },
  {
    GUID: "BCC-21056_20181024_LS_03_07",
    Category: "Labiales",
    SubCategory: "Nude",
    Name: "Ultra Balm",
    Tone: "NUDE CARAMEL",
    Color: "#db856c",
    Description: "Hidrata, Restaura y Protege",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_01",
    Category: "Labiales",
    SubCategory: "Rojos",
    Name: "Infini Dorado Mate",
    Tone: "ROUGE",
    Color: "#A52639",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_02",
    Category: "Labiales",
    SubCategory: "Rojos",
    Name: "Infini Dorado Mate",
    Tone: "MALVE",
    Color: "#812532",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_03",
    Category: "Labiales",
    SubCategory: "Vinos",
    Name: "Infini Dorado Mate",
    Tone: "CHERRY WINE",
    Color: "#72163F",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_04",
    Category: "Labiales",
    SubCategory: "Vinos",
    Name: "Infini Dorado Mate",
    Tone: "RED WINE",
    Color: "#7E172C",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_05",
    Category: "Labiales",
    SubCategory: "Rojos",
    Name: "Infini Dorado Mate",
    Tone: "ROUGE PASSION",
    Color: "#BB0015",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_06",
    Category: "Labiales",
    SubCategory: "Morados",
    Name: "Infini Dorado Mate",
    Tone: "VIOLET",
    Color: "#7D185E",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_07",
    Category: "Labiales",
    SubCategory: "Fucsias",
    Name: "Infini Dorado Mate",
    Tone: "FUXIA PASSION",
    Color: "#CF355B",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_08",
    Category: "Labiales",
    SubCategory: "Fucsias",
    Name: "Infini Dorado Mate",
    Tone: "FUXIA INTENSE",
    Color: "#A11F7F",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_09",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Infini Dorado Mate",
    Tone: "BRAVE",
    Color: "#A43B4A",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_10",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Infini Dorado Mate",
    Tone: "PINK ROSE",
    Color: "#A52639",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_11",
    Category: "Labiales",
    SubCategory: "Nude",
    Name: "Infini Dorado Mate",
    Tone: "PEACH ROSÉ",
    Color: "#C96A64",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_12",
    Category: "Labiales",
    SubCategory: "Marrones",
    Name: "Infini Dorado Mate",
    Tone: "DEEP MOCCA",
    Color: "#48211A",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_13",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Infini Dorado Perlado",
    Tone: "ASTER ROSE",
    Color: "#D58389",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_14",
    Category: "Labiales",
    SubCategory: "Naranjas",
    Name: "Infini Dorado Perlado",
    Tone: "CORAL SCARLAT",
    Color: "#C55A48",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_15",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Infini Dorado Mate",
    Tone: "ROSA BEIGE",
    Color: "#d0766e",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_16",
    Category: "Labiales",
    SubCategory: "Nude",
    Name: "Infini Dorado Mate",
    Tone: "NUDE PEACH",
    Color: "#d37d6c",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_17",
    Category: "Labiales",
    SubCategory: "Marrones",
    Name: "Infini Dorado Mate",
    Tone: "AMANDIER",
    Color: "#924c4c",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_18",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Infini Dorado Metalizado",
    Tone: "ROSE GOLD",
    Color: "#d4857e",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_19",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Infini Dorado Metalizado",
    Tone: "NUDE ROSE",
    Color: "#eab1a1",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_20",
    Category: "Labiales",
    SubCategory: "Marrones",
    Name: "Infini Dorado Metalizado",
    Tone: "COBRE",
    Color: "#d7876b",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_21",
    Category: "Labiales",
    SubCategory: "Marrones",
    Name: "Infini Dorado Metalizado",
    Tone: "BRONZE",
    Color: "#bd775e",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_22",
    Category: "Labiales",
    SubCategory: "Marrones",
    Name: "Infini Dorado Metalizado",
    Tone: "TERRA ACAJOU",
    Color: "#b76b6b",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20200927_SD_01_04",
    Category: "Sombras",
    SubCategory: "Nude",
    Name: "La Palette",
    Tone: "NUDE",
    Description: "Más duración y color",
  },
  {
    GUID: "BCC-21056_20200927_SD_01_03",
    Category: "Sombras",
    SubCategory: "Intensos",
    Name: "La Palette",
    Tone: "GLAMOUR",
    Description: "Más duración y color",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_27",
    Category: "Labiales",
    SubCategory: "Nude",
    Name: "Infini Dorado Mate",
    Tone: "NATURAL ROSE",
    Color: "#9c6257",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_28",
    Category: "Labiales",
    SubCategory: "Fucsias",
    Name: "Infini Dorado Perlado",
    Tone: "FUCSIA",
    Color: "#b11574",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_29",
    Category: "Labiales",
    SubCategory: "Vinos",
    Name: "Infini Dorado Metalizado",
    Tone: "Vin",
    Color: "#7e263f",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_30",
    Category: "Labiales",
    SubCategory: "Vinos",
    Name: "Infini Dorado Metalizado",
    Tone: "Deep Wine",
    Color: "#651a3e",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20220118_FD_01_01",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Base de Maquillaje Antiedad",
    Tone: "Claire 1",
    Color: "#e5af6f",
    Description: "Cubre signos de la edad",
  },
  {
    GUID: "BCC-21056_20220118_FD_01_02",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Base de Maquillaje Antiedad",
    Tone: "Claire 2",
    Color: "#f1a86e",
    Description: "Cubre signos de la edad",
  },
  {
    GUID: "BCC-21056_20220118_FD_01_03",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Base de Maquillaje Antiedad",
    Tone: "Claire 3",
    Color: "#e19d51",
    Description: "Cubre signos de la edad",
  },
  {
    GUID: "BCC-21056_20220118_FD_01_04",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Base de Maquillaje Antiedad",
    Tone: "Claire 4",
    Color: "#df9f6d",
    Description: "Cubre signos de la edad",
  },
  {
    GUID: "BCC-21056_20220118_FD_01_05",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Base de Maquillaje Antiedad",
    Tone: "Medium 5",
    Color: "#d9aa78",
    Description: "Cubre signos de la edad",
  },
  {
    GUID: "BCC-21056_20220118_FD_01_06",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Base de Maquillaje Antiedad",
    Tone: "Medium 6",
    Color: "#c59360",
    Description: "Cubre signos de la edad",
  },
  {
    GUID: "BCC-21056_20220118_FD_01_07",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Base de Maquillaje Antiedad",
    Tone: "Medium 7",
    Color: "#b07956",
    Description: "Cubre signos de la edad",
  },
  {
    GUID: "BCC-21056_20220118_FD_01_08",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Base de Maquillaje Antiedad",
    Tone: "Obscure 8",
    Color: "#9f6d33",
    Description: "Cubre signos de la edad",
  },
  {
    GUID: "BCC-21056_20220118_FD_01_09",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Base de Maquillaje Antiedad",
    Tone: "Obscure 9",
    Color: "#834e24",
    Description: "Cubre signos de la edad",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_49",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Rouge L'Intense Líquido",
    Tone: "Rosé Canelle",
    Color: "#b5577c",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_50",
    Category: "Labiales",
    SubCategory: "Vinos",
    Name: "Rouge L'Intense Líquido",
    Tone: "Vin Violet",
    Color: "#842253",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_51",
    Category: "Labiales",
    SubCategory: "Rojos",
    Name: "Rouge L'Intense Líquido",
    Tone: "Rouge Passion",
    Color: "#b5274d",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_52",
    Category: "Labiales",
    SubCategory: "Fucsias",
    Name: "Rouge L'Intense Líquido",
    Tone: "Pétale Desire",
    Color: "#b04048",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20220215_LS_01_01",
    Category: "Labiales",
    SubCategory: "Rojos",
    Name: "Infini Hydraserum",
    Tone: "CHILLI ROUGE",
    Color: "#a9041c",
    Description: "240% más hidratación en labios",
  },
  {
    GUID: "BCC-21056_20220215_LS_01_02",
    Category: "Labiales",
    SubCategory: "Vinos",
    Name: "Infini Hydraserum",
    Tone: "GRAPE INTENSE",
    Color: "#5c1e3f",
    Description: "240% más hidratación en labios",
  },
  {
    GUID: "BCC-21056_20220215_LS_01_03",
    Category: "Labiales",
    SubCategory: "Fucsias",
    Name: "Infini Hydraserum",
    Tone: "FUCSIA EUPHORIC",
    Color: "#bf3378",
    Description: "240% más hidratación en labios",
  },
  {
    GUID: "BCC-21056_20220215_LS_01_04",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Infini Hydraserum",
    Tone: "BELLE MAUVE",
    Color: "#ad556b",
    Description: "240% más hidratación en labios",
  },
  {
    GUID: "BCC-21056_20220215_LS_01_05",
    Category: "Labiales",
    SubCategory: "Nude",
    Name: "Infini Hydraserum",
    Tone: "PETIT ROSE",
    Color: "#ac4d53",
    Description: "240% más hidratación en labios",
  },
  {
    GUID: "BCC-21056_20220215_LS_01_06",
    Category: "Labiales",
    SubCategory: "Marrones",
    Name: "Infini Hydraserum",
    Tone: "NUDE BRUNE",
    Color: "#9b413b",
    Description: "240% más hidratación en labios",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_31",
    Category: "Labiales",
    SubCategory: "Nude",
    Name: "Infini Dorado Mate",
    Tone: "SPICY ALMOND",
    Color: "#883c2c",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_32",
    Category: "Labiales",
    SubCategory: "Vinos",
    Name: "Infini Dorado Mate",
    Tone: "CINNAMON GLOW",
    Color: "#58041c",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_33",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Infini Dorado Mate",
    Tone: "PINK PEPPER",
    Color: "#802c3c",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210220_BR3D_02_01",
    Category: "Delineadores",
    SubCategory: "Lápiz",
    Name: "Brow Styler Delineador de Cejas",
    Tone: "CASTAÑO",
    Color: "#583c24",
    Description: "Máxima precisión para rellenar",
  },
  {
    GUID: "BCC-21056_20210220_BR3D_02_02",
    Category: "Delineadores",
    SubCategory: "Lápiz",
    Name: "Brow Styler Delineador de Cejas",
    Tone: "CHOCOLATE",
    Color: "#5a4436",
    Description: "Máxima precisión para rellenar",
  },
  {
    GUID: "BCC-21056_20210220_BR3D_02_03",
    Category: "Delineadores",
    SubCategory: "Lápiz",
    Name: "Brow Styler Delineador de Cejas",
    Tone: "CHOCOLATE OSCURO",
    Color: "#443433",
    Description: "Máxima precisión para rellenar",
  },
  {
    GUID: "BCC-21056_20210220_BR3D_02_04",
    Category: "Delineadores",
    SubCategory: "Lápiz",
    Name: "Brow Styler Delineador de Cejas",
    Tone: "EXPRESSO",
    Color: "#372e2f",
    Description: "Máxima precisión para rellenar",
  },
  {
    GUID: "BCC-21056_20190725_SD_01_01",
    Category: "Cejas",
    SubCategory: "Polvos",
    Name: "Estuche Perfeccionador de Cejas y Ojos",
    Description: "Perfecciona, enmarca y define",
  },
  {
    GUID: "BCC-21056_20201008_FD_02_25",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Aclaradora De Manchas Clarité",
    Tone: "390-N",
    Color: "#b4835a",
    Description: "Minimiza y aclara de manchas",
  },
  {
    GUID: "BCC-21056_20201008_FD_02_27",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Aclaradora De Manchas Clarité",
    Tone: "420-C",
    Color: "#916244",
    Description: "Minimiza y aclara de manchas",
  },
  {
    GUID: "BCC-21056_20201008_FD_02_29",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Aclaradora De Manchas Clarité",
    Tone: "460-F",
    Color: "#7d523f",
    Description: "Minimiza y aclara de manchas",
  },
  {
    GUID: "BCC-21056_20210625_FD_01_12",
    Category: "Bases",
    SubCategory: "Natural",
    Name: "Concentré Total Sérum",
    Tone: "AVELLANA",
    Color: "#c99570",
    Description: "5 beneficios en 1",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_45",
    Category: "Labiales",
    SubCategory: "Rojos",
    Name: "Infini Absolu",
    Tone: "Rouge Glorieux",
    Color: "#952017",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_35",
    Category: "Labiales",
    SubCategory: "Vinos",
    Name: "Infini Absolu",
    Tone: "Burgundy Wine",
    Color: "#5c1229",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_46",
    Category: "Labiales",
    SubCategory: "Vinos",
    Name: "Infini Absolu",
    Tone: "Mauve Nuit",
    Color: "#5c1e37",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_47",
    Category: "Labiales",
    SubCategory: "Rojos",
    Name: "Infini Absolu",
    Tone: "Passion Adore",
    Color: "#65111e",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_48",
    Category: "Labiales",
    SubCategory: "Morados",
    Name: "Infini Absolu",
    Tone: "Vivid Violet",
    Color: "#783c62",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_30",
    Category: "Labiales",
    SubCategory: "Fucsias",
    Name: "Infini Absolu",
    Tone: "Profond framboise",
    Color: "#cc045d",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_49",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Infini Absolu",
    Tone: "Pink Noveau",
    Color: "#ce4482",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_32",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Infini Absolu",
    Tone: "Bonbon rosé",
    Color: "#9e4a59",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_37",
    Category: "Labiales",
    SubCategory: "Nudes",
    Name: "Infini Absolu",
    Tone: "Rose Latte",
    Color: "#9a4a4b",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_38",
    Category: "Labiales",
    SubCategory: "Nudes",
    Name: "Infini Absolu",
    Tone: "Caramel Mocha",
    Color: "#a75a50",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_39",
    Category: "Labiales",
    SubCategory: "Nudes",
    Name: "Infini Absolu",
    Tone: "Sweet Machiatto",
    Color: "#8a434b",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_40",
    Category: "Labiales",
    SubCategory: "Marrones",
    Name: "Infini Absolu",
    Tone: "Cocoa bitter",
    Color: "#592319",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_33",
    Category: "Labiales",
    SubCategory: "Corales",
    Name: "Infini Absolu",
    Tone: "Citrique éclat",
    Color: "#b3372f",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_01",
    Category: "Labiales",
    SubCategory: "Rojos",
    Name: "Infini Absolu",
    Tone: "VIN ÉXUBERANT",
    Color: "#a00024",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_08",
    Category: "Labiales",
    SubCategory: "Fucsias",
    Name: "Infini Absolu",
    Tone: "FRAISE RADIANT",
    Color: "#e50052",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_06",
    Category: "Labiales",
    SubCategory: "Rojos",
    Name: "Infini Absolu",
    Tone: "ROUGE EXCITANT",
    Color: "#c00321",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_07",
    Category: "Labiales",
    SubCategory: "Fucsias",
    Name: "Infini Absolu",
    Tone: "FUCSIA VIF",
    Color: "#fb06ab",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_04",
    Category: "Labiales",
    SubCategory: "Morados",
    Name: "Infini Absolu",
    Tone: "VIOLET SUPRÊME",
    Color: "#a61b82",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_20",
    Category: "Labiales",
    SubCategory: "Marrones",
    Name: "Infini Absolu",
    Tone: "DARK CINNAMON",
    Color: "#8a3027",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_17",
    Category: "Labiales",
    SubCategory: "Nudes",
    Name: "Infini Absolu",
    Tone: "PEACH",
    Color: "#d15c4b",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_15",
    Category: "Labiales",
    SubCategory: "Morados",
    Name: "Infini Absolu",
    Tone: "VIOLET CASSIS",
    Color: "#6e0258",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_50",
    Category: "Labiales",
    SubCategory: "Fucsias",
    Name: "Infini Absolu",
    Tone: "VERY FUCSIA",
    Color: "#bf2b7f",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_51",
    Category: "Labiales",
    SubCategory: "Rojos",
    Name: "Infini Absolu",
    Tone: "CHARMANT RED",
    Color: "#bb2b22",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_52",
    Category: "Labiales",
    SubCategory: "Rojos",
    Name: "Infini Absolu",
    Tone: "ICONIC RED",
    Color: "#c0070f",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_44",
    Category: "Labiales",
    SubCategory: "Marrones",
    Name: "Rouge L'Intense Líquido",
    Tone: "CARAMEL MOUSSE",
    Color: "#9d1b3b",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_40",
    Category: "Labiales",
    SubCategory: "Vinos",
    Name: "Rouge L'Intense Líquido",
    Tone: "VIN GLAMOUR",
    Color: "#bb3153",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_39",
    Category: "Labiales",
    SubCategory: "Nude",
    Name: "Rouge L'Intense Líquido",
    Tone: "ROSÉ NUDE",
    Color: "#b56367",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_35",
    Category: "Labiales",
    SubCategory: "Vinos",
    Name: "Rouge L'Intense Líquido",
    Tone: "CHERRY BRANDY",
    Color: "#650937",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_36",
    Category: "Labiales",
    SubCategory: "Fucsias",
    Name: "Rouge L'Intense Líquido",
    Tone: "CRANBERRY",
    Color: "#90144b",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_38",
    Category: "Labiales",
    SubCategory: "Nude",
    Name: "Rouge L'Intense Líquido",
    Tone: "APRICOT NUDE",
    Color: "#bd796c",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_31",
    Category: "Labiales",
    SubCategory: "Nude",
    Name: "Rouge L'Intense Líquido",
    Tone: "SWEET NUDE",
    Color: "#cc5d61",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_11",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Rouge L'Intense Líquido",
    Tone: "ROSE DESIR",
    Color: "#e56e83",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_25",
    Category: "Labiales",
    SubCategory: "Rojos",
    Name: "Rouge L'Intense Líquido",
    Tone: "RUBI",
    Color: "#780d11",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_14",
    Category: "Labiales",
    SubCategory: "Nude",
    Name: "Rouge L'Intense Líquido",
    Tone: "NUDE",
    Color: "#ba6761",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_02",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Rouge L'Intense Líquido",
    Tone: "MAUVE ROSE",
    Color: "#9e3854",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_15",
    Category: "Labiales",
    SubCategory: "Fucsias",
    Name: "Rouge L'Intense Líquido",
    Tone: "VIN AMANT",
    Color: "#8a233a",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_21",
    Category: "Labiales",
    SubCategory: "Vinos",
    Name: "Rouge L'Intense Líquido",
    Tone: "VIN INTENSE",
    Color: "#702534",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_17",
    Category: "Labiales",
    SubCategory: "Fucsias",
    Name: "Rouge L'Intense Líquido",
    Tone: "FRAMBOISE",
    Color: "#cd294e",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_18",
    Category: "Labiales",
    SubCategory: "Rojos",
    Name: "Rouge L'Intense Líquido",
    Tone: "CERISE",
    Color: "#a8173b",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_22",
    Category: "Labiales",
    SubCategory: "Rojos",
    Name: "Rouge L'Intense Líquido",
    Tone: "ROUGE",
    Color: "#8a0b17",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_24",
    Category: "Labiales",
    SubCategory: "Rojos",
    Name: "Rouge L'Intense Líquido",
    Tone: "ROUGE VIBRANT",
    Color: "#b91524",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_23",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Rouge L'Intense Líquido",
    Tone: "ROSELLE",
    Color: "#aa2f48",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_53",
    Category: "Labiales",
    SubCategory: "Rojos",
    Name: "Rouge L'Intense Líquido",
    Tone: "PARISSIAN KISS",
    Color: "#8f031e",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_54",
    Category: "Labiales",
    SubCategory: "Morados",
    Name: "Rouge L'Intense Líquido",
    Tone: "VIE EN ROSÉ",
    Color: "#a4407e",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_55",
    Category: "Labiales",
    SubCategory: "Fucsias",
    Name: "Rouge L'Intense Líquido",
    Tone: "FUCSIA EUPHORIA",
    Color: "#d60666",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_34",
    Category: "Labiales",
    SubCategory: "Rojos",
    Name: "Infini Dorado Mate",
    Tone: "ROUGE BONBON",
    Color: "#97122f",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_35",
    Category: "Labiales",
    SubCategory: "Vinos",
    Name: "Infini Dorado Mate",
    Tone: "SWEET BURGUNDY",
    Color: "#681437",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_36",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Infini Dorado Mate",
    Tone: "PINK MACARROOON",
    Color: "#da4e7a",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20210205_LS_01_37",
    Category: "Labiales",
    SubCategory: "Fucsias",
    Name: "Infini Dorado Mate",
    Tone: "FRAISE JELLY",
    Color: "#920f3b",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20220215_LS_01_07",
    Category: "Labiales",
    SubCategory: "Rojos",
    Name: "Infini Hydraserum",
    Tone: "VIN EXUBERANT",
    Color: "#b5092b",
    Description: "240% más hidratación en labios",
  },
  {
    GUID: "BCC-21056_20220215_LS_01_08",
    Category: "Labiales",
    SubCategory: "Vinos",
    Name: "Infini Hydraserum",
    Tone: "VIN NOIR",
    Color: "#731237",
    Description: "240% más hidratación en labios",
  },
  {
    GUID: "BCC-21056_20220215_LS_01_09",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Infini Hydraserum",
    Tone: "ROSE CELEBRITE",
    Color: "#91343a",
    Description: "240% más hidratación en labios",
  },
  {
    GUID: "BCC-21056_20220215_LS_01_10",
    Category: "Labiales",
    SubCategory: "Nudes",
    Name: "Infini Hydraserum",
    Tone: "NUDE INTENSE",
    Color: "#91554a",
    Description: "240% más hidratación en labios",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_53",
    Category: "Labiales",
    SubCategory: "Vinos",
    Name: "Infini Absolu",
    Tone: "WARM WINE",
    Color: "#701d4c",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_54",
    Category: "Labiales",
    SubCategory: "Fucsias",
    Name: "Infini Absolu",
    Tone: "FUCSIA FLAMINGO",
    Color: "#b73271",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_55",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Infini Absolu",
    Tone: "MYSTIC ROSÉ",
    Color: "#8f4b50",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20220602_FD_01_01",
    Category: "Polvos",
    SubCategory: "Mate",
    Name: "Polvos Concentré",
    Tone: "CLAIRE 1-2-3",
    Color: "#f3c9a0",
    Description: "Triple poder antiedad",
  },
  {
    GUID: "BCC-21056_20220602_FD_01_02",
    Category: "Polvos",
    SubCategory: "Mate",
    Name: "Polvos Concentré",
    Tone: "CLAIRE 4",
    Color: "#f6c69c",
    Description: "Triple poder antiedad",
  },
  {
    GUID: "BCC-21056_20220602_FD_01_03",
    Category: "Polvos",
    SubCategory: "Mate",
    Name: "Polvos Concentré",
    Tone: "MEDIUM 5",
    Color: "#e1ac83",
    Description: "Triple poder antiedad",
  },
  {
    GUID: "BCC-21056_20220602_FD_01_04",
    Category: "Polvos",
    SubCategory: "Mate",
    Name: "Polvos Concentré",
    Tone: "MEDIUM 6",
    Color: "#e3a979",
    Description: "Triple poder antiedad",
  },
  {
    GUID: "BCC-21056_20220602_FD_01_05",
    Category: "Polvos",
    SubCategory: "Mate",
    Name: "Polvos Concentré",
    Tone: "MEDIUM 7",
    Color: "#d8a985",
    Description: "Triple poder antiedad",
  },
  {
    GUID: "BCC-21056_20220602_FD_01_06",
    Category: "Polvos",
    SubCategory: "Mate",
    Name: "Polvos Concentré",
    Tone: "OBSCURE 8-9",
    Color: "#cd996d",
    Description: "Triple poder antiedad",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_56",
    Category: "Labiales",
    SubCategory: "Vinos",
    Name: "Rouge L'Intense Líquido",
    Tone: "MERLOT NUDE",
    Color: "#440804",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_57",
    Category: "Labiales",
    SubCategory: "Nude",
    Name: "Rouge L'Intense Líquido",
    Tone: "DEEP NUDE",
    Color: "#905757",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_58",
    Category: "Labiales",
    SubCategory: "Nude",
    Name: "Rouge L'Intense Líquido",
    Tone: "NUDE CHARMÉ",
    Color: "#95555d",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20220723_FD_01_01",
    Category: "Bases",
    SubCategory: "Mate",
    Name: "Base Nude Skin",
    Tone: "CHAMPAGNE 170N",
    Color: "#dbb89b",
    Description: "Hidratación inmediata con vitaminas",
  },
  {
    GUID: "BCC-21056_20220723_FD_01_02",
    Category: "Bases",
    SubCategory: "Natural",
    Name: "Base Nude Skin",
    Tone: "LATTE 180F",
    Color: "#c29d85",
    Description: "Hidratación inmediata con vitaminas",
  },
  {
    GUID: "BCC-21056_20220723_FD_01_03",
    Category: "Bases",
    SubCategory: "Natural",
    Name: "Base Nude Skin",
    Tone: "CREME 110C",
    Color: "#d7b7a0",
    Description: "Hidratación inmediata con vitaminas",
  },
  {
    GUID: "BCC-21056_20220723_FD_01_04",
    Category: "Bases",
    SubCategory: "Natural",
    Name: "Base Nude Skin",
    Tone: "CARAMEL 210F",
    Color: "#c29372",
    Description: "Hidratación inmediata con vitaminas",
  },
  {
    GUID: "BCC-21056_20220723_FD_01_05",
    Category: "Bases",
    SubCategory: "Natural",
    Name: "Base Nude Skin",
    Tone: "ALMENDRA 230N",
    Color: "#bc8f6b",
    Description: "Hidratación inmediata con vitaminas",
  },
  {
    GUID: "BCC-21056_20220723_FD_01_06",
    Category: "Bases",
    SubCategory: "Natural",
    Name: "Base Nude Skin",
    Tone: "BEIGE 220C",
    Color: "#d3b18d",
    Description: "Hidratación inmediata con vitaminas",
  },
  {
    GUID: "BCC-21056_20220723_FD_01_07",
    Category: "Bases",
    SubCategory: "Natural",
    Name: "Base Nude Skin",
    Tone: "AVELLANA 270C",
    Color: "#b68a6a",
    Description: "Hidratación inmediata con vitaminas",
  },
  {
    GUID: "BCC-21056_20220723_FD_01_08",
    Category: "Bases",
    SubCategory: "Natural",
    Name: "Base Nude Skin",
    Tone: "MOKACCHINO 390N",
    Color: "#946f54",
    Description: "Hidratación inmediata con vitaminas",
  },
  {
    GUID: "BCC-21056_20220723_FD_01_09",
    Category: "Bases",
    SubCategory: "Natural",
    Name: "Base Nude Skin",
    Tone: "CACAO 350N",
    Color: "#a17557",
    Description: "Hidratación inmediata con vitaminas",
  },
  {
    GUID: "BCC-21056_20220723_FD_01_10",
    Category: "Bases",
    SubCategory: "Natural",
    Name: "Base Nude Skin",
    Tone: "CAPUCCINO 310C",
    Color: "#b5896c",
    Description: "Hidratación inmediata con vitaminas",
  },
  {
    GUID: "BCC-21056_20220723_FD_01_11",
    Category: "Bases",
    SubCategory: "Natural",
    Name: "Base Nude Skin",
    Tone: "CHOCOLATE 460F",
    Color: "#543726",
    Description: "Hidratación inmediata con vitaminas",
  },
  {
    GUID: "BCC-21056_20220723_FD_01_12",
    Category: "Bases",
    SubCategory: "Natural",
    Name: "Base Nude Skin",
    Tone: "MOKA 420C",
    Color: "#7a543c",
    Description: "Hidratación inmediata con vitaminas",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_59",
    Category: "Labiales",
    SubCategory: "Rojos",
    Name: "Rouge L'Intense Líquido",
    Tone: "PARIS ROUGE",
    Color: "#6e082d",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_60",
    Category: "Labiales",
    SubCategory: "Marrones",
    Name: "Rouge L'Intense Líquido",
    Tone: "MORROCO TERRE",
    Color: "#8c3b2c",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_61",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Rouge L'Intense Líquido",
    Tone: "ROMANTIQUE",
    Color: "#bc5c80",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_62",
    Category: "Labiales",
    SubCategory: "Corales",
    Name: "Rouge L'Intense Líquido",
    Tone: "CORAL CHARME",
    Color: "#bc5b54",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_63",
    Category: "Labiales",
    SubCategory: "Naranjas",
    Name: "Rouge L'Intense Líquido",
    Tone: "ROUGE MANDARIN",
    Color: "#94241c",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_64",
    Category: "Labiales",
    SubCategory: "Morados",
    Name: "Rouge L'Intense Líquido",
    Tone: "SOFT MALVA",
    Color: "#8c545c",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_65",
    Category: "Labiales",
    SubCategory: "Nude",
    Name: "Rouge L'Intense Líquido",
    Tone: "MOCCA NUDE",
    Color: "#9c6464",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_66",
    Category: "Labiales",
    SubCategory: "Fucsias",
    Name: "Rouge L'Intense Líquido",
    Tone: "FUCSIA VIBRANT",
    Color: "#c4347c",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_67",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Rouge L'Intense Líquido",
    Tone: "MOCCHA",
    Color: "#8c5443",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_05_68",
    Category: "Labiales",
    SubCategory: "Marrones",
    Name: "Rouge L'Intense Líquido",
    Tone: "BORDELAIS",
    Color: "#7b3434",
    Description: "Mate y textura aterciopelada",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_56",
    Category: "Labiales",
    SubCategory: "Vinos",
    Name: "Infini Absolu",
    Tone: "CARAMEL PECAN",
    Color: "#5c3434",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_57",
    Category: "Labiales",
    SubCategory: "Rosas",
    Name: "Infini Absolu",
    Tone: "PINK DELIGHT",
    Color: "#a45c71",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20181024_LS_04_58",
    Category: "Labiales",
    SubCategory: "Rojos",
    Name: "Infini Absolu",
    Tone: "CHERRY FONDANT",
    Color: "#a4040c",
    Description: "Hidrata con ácido hialurónico",
  },
  {
    GUID: "BCC-21056_20220802_LA_01_01",
    Category: "Máscaras",
    SubCategory: "Definición",
    Name: "Mascara Definition",
    Tone: "NOIR",
    Color: "#000000",
    Description: "Efecto multiplicador",
  },
];
export default data;
